version = 5.3.1
archive_dir = /etc/letsencrypt/archive/npm-8
cert = /etc/letsencrypt/live/npm-8/cert.pem
privkey = /etc/letsencrypt/live/npm-8/privkey.pem
chain = /etc/letsencrypt/live/npm-8/chain.pem
fullchain = /etc/letsencrypt/live/npm-8/fullchain.pem
[renewalparams]
account = 35afb77c33fff5faf35e394b6367497d
key_type = ecdsa
elliptic_curve = secp384r1
preferred_chain = ISRG Root X1
pref_challs = http-01,
config_dir = /etc/letsencrypt
work_dir = /tmp/letsencrypt-lib
logs_dir = /data/logs
authenticator = webroot
webroot_path = /data/letsencrypt-acme-challenge,
server = https://acme-v02.api.letsencrypt.org/directory
[[webroot_map]]
perjadinbkad.ddns.net = /data/letsencrypt-acme-challenge
