services:

  postgres:
    image: postgres:16

    container_name: postgres

    restart: always

    environment:
      POSTGRES_USER: raselstr
      POSTGRES_PASSWORD: r283l8tr

    ports:
      - "5432:5432"

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/backup

    networks:
      - production_network

networks:
  production_network:
    external: true